// shards
#define SHARD_NONE		0
#define SHARD_CRITICAL	1
#define SHARD_POISONING	2
#define SHARD_RIGHTEOUS	3
#define SHARD_UNUSED	4	// UNUSED
#define SHARD_AGILE		5
#define SHARD_LIGHT		6
#define SHARD_SHARP		7
#define SHARD_STRONG	8
#define SHARD_ANCIENT	9
#define SHARD_CASTPROB	10
#define SHARD_MANACONV	11
#define SHARD_CRITICAL2	12

// fragments
#define FRAGMENT_NONE		0
#define FRAGMENT_PSNRES		1
#define FRAGMENT_HITPROB	2
#define FRAGMENT_DEF		3
#define FRAGMENT_HPREC		4
#define FRAGMENT_SPREC		5
#define FRAGMENT_MPREC		6
#define FRAGMENT_MR			7
#define FRAGMENT_PA			8
#define FRAGMENT_MA			9
#define FRAGMENT_CAD		10
#define FRAGMENT_EXP		11
#define FRAGMENT_GOLD		12


#define UPGRADEONE_SHARD 0
#define UPGRADEONE_FRAGMENT 1
#define UPGRADEALL_SHARD 10
#define UPGRADEALL_FRAGMENT 11

#define DEF_MAXCRUSADESTRUCTURES		300
